# Generated by Django 5.1.3 on 2025-12-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DHT", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Incident",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("type_incident", models.CharField(max_length=100)),
                ("niveau_urgence", models.CharField(default="CRITIQUE", max_length=20)),
                ("est_traite", models.BooleanField(default=False)),
                ("traite_par", models.CharField(blank=True, max_length=100, null=True)),
                ("date_traitement", models.DateTimeField(blank=True, null=True)),
                ("note_intervention", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
