# Generated by Django 5.1.3 on 2025-12-09 19:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DHT", "0002_incident"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="incident",
            name="date_creation",
        ),
        migrations.RemoveField(
            model_name="incident",
            name="est_traite",
        ),
        migrations.RemoveField(
            model_name="incident",
            name="niveau_urgence",
        ),
        migrations.RemoveField(
            model_name="incident",
            name="traite_par",
        ),
        migrations.RemoveField(
            model_name="incident",
            name="type_incident",
        ),
        migrations.AlterField(
            model_name="incident",
            name="date_traitement",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="incident",
            name="note_intervention",
            field=models.CharField(default="Alarme acquittée", max_length=200),
        ),
    ]
