# Generated by Django 5.1.3 on 2025-12-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DHT", "0003_remove_incident_date_creation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="incident",
            name="compteur_niveau",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="incident",
            name="traite_par",
            field=models.CharField(default="Opérateur 1", max_length=100),
        ),
    ]
