# Generated by Django 5.1.3 on 2025-12-15 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DHT", "0004_incident_compteur_niveau_incident_traite_par"),
    ]

    operations = [
        migrations.AlterField(
            model_name="incident",
            name="note_intervention",
            field=models.CharField(default="RAS", max_length=200),
        ),
        migrations.AlterField(
            model_name="incident",
            name="traite_par",
            field=models.CharField(default="Inconnu", max_length=100),
        ),
    ]
