# Generated by Django 5.2.7 on 2026-01-03 17:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0005_alter_incident_note_intervention_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='incident',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='last_dht_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='incident',
            name='max_temp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='op1_ack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incident',
            name='op1_comment',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='incident',
            name='op2_ack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incident',
            name='op2_comment',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='incident',
            name='op3_ack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incident',
            name='op3_comment',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='dht11',
            name='hum',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dht11',
            name='temp',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
