# Generated by Django 5.2.7 on 2026-01-03 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0006_incident_counter_incident_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='compteur_niveau',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='date_traitement',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='last_dht_id',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='note_intervention',
        ),
        migrations.RemoveField(
            model_name='incident',
            name='traite_par',
        ),
        migrations.AddField(
            model_name='incident',
            name='kind',
            field=models.CharField(choices=[('HOT', 'HOT'), ('COLD', 'COLD')], default='HOT', max_length=4),
        ),
        migrations.AddField(
            model_name='incident',
            name='last_counter_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dht11',
            name='hum',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dht11',
            name='temp',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='op1_comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='op2_comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='op3_comment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
