# Generated by Django 5.2.7 on 2026-01-04 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0007_remove_incident_compteur_niveau_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='temp_max_autorisee',
            field=models.FloatField(default=8.0),
        ),
        migrations.AddField(
            model_name='incident',
            name='temp_min_autorisee',
            field=models.FloatField(default=2.0),
        ),
        migrations.AlterField(
            model_name='dht11',
            name='hum',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dht11',
            name='temp',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OperateurProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=60)),
                ('prenom', models.CharField(max_length=60)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('niveau', models.PositiveSmallIntegerField(default=1)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operateur_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
