# Generated by Django 5.2.7 on 2026-01-06 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0008_incident_temp_max_autorisee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operateurprofile',
            name='telegram',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
