# Generated by Django 5.2.7 on 2026-01-07 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0009_operateurprofile_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='last_dht_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
