# Generated by Django 5.2.7 on 2026-01-07 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0010_incident_last_dht_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='IoTSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_min', models.FloatField(default=2.0)),
                ('temp_max', models.FloatField(default=8.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Réglages IoT',
                'verbose_name_plural': 'Réglages IoT',
            },
        ),
    ]
