# Generated by Django 5.2.7 on 2026-01-09 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DHT', '0011_iotsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='notified_lvl1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incident',
            name='notified_lvl2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='incident',
            name='notified_lvl3',
            field=models.BooleanField(default=False),
        ),
    ]
